### ISSUE TITLE
Error: Project name could not be inferred. Please specify the `projectName` option.

### ISSUE THREAD

**Issue by Angelk90** [vadimdemedes/switch-branch-cli#3]
Hi @vadimdemedes , 
I am testing the library but am having some doubts about the correct use.

I tried running the command on two different git repositories and I get the following messages:

Project1(error): 

```
/Users/Username/.nvm/versions/node/v16.14.2/lib/node_modules/switch-branch-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Project name could not be inferred. Please specify the `projectName` option.
    at new Conf (/Users/Username/.nvm/versions/node/v16.14.2/lib/node_modules/switch-branch-cli/node_modules/conf/dist/source/index.js:90:23)
    at file:///Users/Username/.nvm/versions/node/v16.14.2/lib/node_modules/switch-branch-cli/dist/cli.js:133:14
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
```

Project2: 

```
  This CLI requires a personal access token for your GitHub account.
  It's used for fetching your pull requests and only needs to be entered once.

  Press Enter to create it.
```

The message I get on project2, I believe is correct.
How come on project1, instead I get error?

**Comment by vadimdemedes** [comment]
Interesting, will take a look.

**Comment by Angelk90** [comment]
@vadimdemedes : Are there any news?

**Comment by LitoMore** [comment]
@Angelk90 That's because your `package.json` does not have the `name` field. `Conf` requires the `projectName` for creating a storage path.

You can reproduce the bug in any other non-Node.js project.

**Comment by LitoMore** [comment]
@vadimdemedes I think we should use another string as its identifier. For example the git remote path or project absolute path.

See: https://github.com/sindresorhus/conf#projectname
