### ISSUE TITLE
Get error after entering token

### ISSUE THREAD

**Issue by nikivdev** [vadimdemedes/switch-branch-cli#5]
I went through auth phase. Copied and pasted token correctly I think.

Then when I try to run it on a project I get:

```
switch-branch


/Users/nikiv/Library/Application Support/fnm/node-versions/v17.9.0/installation/lib/node_modules/switch-branch-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

TypeError: Cannot read properties of undefined (reading 'value')
    at file:///Users/nikiv/Library/Application%20Support/fnm/node-versions/v17.9.0/installation/lib/node_modules/switch-branch-cli/dist/cli.js:248:22
    at /Users/nikiv/Library/Application Support/fnm/node-versions/v17.9.0/installation/lib/node_modules/switch-branch-cli/node_modules/ink-select-input/build/SelectInput.js:61:17
    at ReadStream.handleData (/Users/nikiv/Library/Application Support/fnm/node-versions/v17.9.0/installation/lib/node_modules/switch-branch-cli/node_modules/ink/build/hooks/use-input.js:88:17)
    at ReadStream.emit (node:events:539:35)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:293:11)
    at ReadStream.Readable.push (node:internal/streams/readable:234:10)
    at TTY.onStreamRead (node:internal/stream_base_commons:190:23)

Node.js v17.9.0
```

**Comment by vadimdemedes** [comment]
Another person reported this issue today too. I suspect it happens when user doesn't have any pull requests open.

**Comment by LitoMore** [comment]
I found the root cause. I commented in #3.
